name: 'Eksctl tool installer'
description: 'Install a specific version of eksctl for AWS Elastic Kubernetes Service (EKS).'
inputs:
  version:
    description: 'Version of eksctl'
    required: true
    default: 'latest'
outputs:
  eksctl-path:
    description: 'Path to the cached eksctl binary'
branding:
  color: 'red'
runs:
  using: 'node16'
  main: 'lib/run.js'
