name: 'Eksctl tool installer'
description: 'Install a specific version of eksctl for AWS Elastic Kubernetes Service (EKS). You must provide a valid semantic version string like 0.56.0'
inputs: 
  version:
    description: 'Version of eksctl'
    required: true
    default: '0.56.0'
outputs:
  eksctl-path:
    description: 'Path to the cached eksctl binary'
branding:
  color: 'red'
runs:
  using: 'node12'
  main: 'lib/run.js'